name: Publish on crates.io

on:
  push:
    branches: [ 'release' ]

env:
  CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cargo setup
      run: |
        rustup update
        cargo login ${CRATES_IO_TOKEN}
    - name: Publish
      run: cargo publish
