name: Release proto

on:
  push:
    branches: [ new-proto ]
    paths-ignore: [ '.github/**' ]

env:
  BRANCH_TO_PUSH: release

jobs:
  update-proro:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Git setup
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github@s.k-kachi.net"
        git config --global push.default current
        git fetch origin ${BRANCH_TO_PUSH}
        git checkout -b ${BRANCH_TO_PUSH} origin/${BRANCH_TO_PUSH}
        git merge new-proto
    - name: Cargo setup
      run: |
        rustup update
        cargo install cargo-bump
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Bump version
      run: cargo bump minor --git-tag
    - name: Git push
      run: git push && git push origin --tags
