name: Update proto

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-proto:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Git setup
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github@s.k-kachi.net"
        git config --global push.default current
        git fetch origin master
        git checkout -B master origin/master
    - name: Update proto
      run: |
        bash update.sh
        git add .
        git commit -m "Update proto" && echo "NEW_PROTOS_RELEASE=true" >> $GITHUB_ENV || echo "Protos are up-to-date."
    - name: Push
      if: ${{ env.NEW_PROTOS_RELEASE }}
      run: |
        rustup update
        cargo install cargo-bump
        cargo bump minor --git-tag
        git push
        git push origin --tags
