name: Update proto

on:
  schedule:
    - cron: "0 0 * * 0"

env:
  BRANCH_TO_PUSH: new-proto

jobs:
  update-proro:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Git setup
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github@s.k-kachi.net"
        git config --global push.default current
        git fetch origin release
        git checkout -B ${BRANCH_TO_PUSH} origin/release
    - name: Update proto
      run: bash update.sh
    - name: Commit and push
      run: git add . && git commit -m "Update proto" && git push -f || echo "Protos are up-to-date."
