name: Update proto

on:
  schedule:
    - cron: "0 0 * * 0"

env:
  CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

jobs:
  update-proto:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Git setup
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github@s.k-kachi.net"
        git config --global push.default current
        git fetch origin master
        git checkout -B master origin/master
    - name: Update proto
      run: |
        bash update.sh
        git add .
        git commit -m "Update proto" && echo "NEW_PROTOS_RELEASE=true" >> $GITHUB_ENV || echo "Protos are up-to-date."
    - name: Push
      if: ${{ env.NEW_PROTOS_RELEASE }}
      run: |
        rustup update
        cargo install cargo-bump
        cargo bump minor --git-tag
        git push
        git push origin --tags
    - name: Cargo setup
      run: |
        rustup update
        rustup component add rustfmt
        cargo login ${CRATES_IO_TOKEN}
    - name: Publish
      run: cargo publish
    - name: Setup documents
      run: |
        cargo doc --lib
        echo '<!DOCTYPE html><html><head><meta http-equiv=refresh content="0; URL=firestore_grpc/index.html"><title>x</title></head><body>x</body></html>' > target/doc/index.html
    - name: Deploy documents
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: target/doc

